export const tw = {
  appShell: 'font-sans antialiased',
  label: 'font-sans text-[11px] uppercase tracking-[0.18em]',
  value: 'font-mono tabular-nums',
}

export const colors = {
  void: 'var(--mt-void)',
  voidDeep: 'var(--mt-void-deep)',
  surfaceRaised: 'var(--mt-surface-raised)',
  chalk: 'var(--mt-chalk)',
  mist: 'var(--mt-mist)',
  line: 'var(--mt-line)',
  copper: 'var(--mt-copper)',
  copperGlow: 'var(--mt-copper-glow)',
  copperDim: 'var(--mt-copper-dim)',
  teal: 'var(--mt-teal)',
  mouseShell: 'var(--mt-mouse-shell)',
  mouseShellLit: 'var(--mt-mouse-shell-lit)',
  mouseStroke: 'var(--mt-mouse-stroke)',
  mouseBtn: 'var(--mt-mouse-btn)',
  mouseBtnPressed: 'var(--mt-mouse-btn-pressed)',
  mouseBtnText: 'var(--mt-mouse-btn-text)',
  mouseBtnTextOn: 'var(--mt-mouse-btn-text-on)',
  padFill: 'var(--mt-pad-fill)',
  padRing: 'var(--mt-pad-ring)',
  padRingDim: 'var(--mt-pad-ring-dim)',
  padGlow: 'var(--mt-pad-glow)',
  padDim: 'var(--mt-pad-dim)',
}
