import type { PlayerKeymap } from './keymap'

export function buildConfigTxt(keymap: PlayerKeymap): string {
  const lines: (string | number)[] = [
    keymap.dpadUp.gamepad ?? 12,
    keymap.dpadDown.gamepad ?? 13,
    keymap.dpadLeft.gamepad ?? 14,
    keymap.dpadRight.gamepad ?? 15,
    keymap.a.gamepad ?? 0,
    keymap.b.gamepad ?? 2,
    keymap.start.gamepad ?? 9,
    keymap.z.gamepad ?? 4,
    keymap.l.gamepad ?? 6,
    keymap.r.gamepad ?? 5,
    11,
    keymap.cLeft.gamepad ?? -1,
    keymap.cRight.gamepad ?? -1,
    keymap.cUp.gamepad ?? -1,
    keymap.cDown.gamepad ?? -1,
    keymap.dpadLeft.key,
    keymap.dpadRight.key,
    keymap.dpadUp.key,
    keymap.dpadDown.key,
    keymap.start.key,
    keymap.cUp.key,
    keymap.cDown.key,
    keymap.cLeft.key,
    keymap.cRight.key,
    keymap.z.key,
    keymap.l.key,
    keymap.r.key,
    keymap.b.key,
    keymap.a.key,
    '`',
    keymap.analogUp.key,
    keymap.analogDown.key,
    keymap.analogLeft.key,
    keymap.analogRight.key,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  ]
  return lines.join('\r\n') + '\r\n'
}
